name: Generate Snake Game SVG

on:
  schedule:
    - cron: "0 0 * * *"  # Her gece çalıştır
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake.svg  # 'outputs' yerine doğru parametre

      - name: Push Snake Game SVG to Profile Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
